#!/usr/bin/env python3
from gpiozero import Button
import os
Button(4).wait_for_press()
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /etc/teste aluno@191.36.8.34 killall -9 mate-session")
os.system("ssh -p 22 -i /root/.ssh/root root@191.36.8.34 rm -r /home/aluno")
os.system("ssh -p 22 -i /root/.ssh/root root@191.36.8.34 tar -zxvf /etc/.aluno.tar.gz -C /home")
os.system("ssh -p 22 -i /root/.ssh/root root@191.36.8.34 chown -R aluno:aluno /home/aluno")
os.system("ssh -p 22 -i /root/.ssh/root root@191.36.8.34 chown -R root:root /home/aluno/.ssh/authorized_keys")
# os.system("mv /home/aluno/.x2goclient /home")
os.system("rm -r /home/aluno")
os.system("cp -r /etc/home/.aluno /home/aluno")
# os.system("mv /home/.x2goclient /home/aluno")
os.system("chown -R aluno:aluno /home/aluno")
os.system("chown -R root:root /home/aluno/.profile")
os.system("chmod -R 744 /home/aluno/.profile")
os.system("chown -R root:root /home/aluno/.xinitrc")
os.system("chmod -R 744 /home/aluno.xinitrc")
# os.system("chown -R root:root /home/aluno/.x2goclient")
# os.system("chmod -R 744 /home/aluno/.x2goclient")
os.system("rm -r /home/sdr")
os.system("cp -r /etc/home/.sdr /home/sdr")
os.system("systemctl reboot")
