#!/bin/bash

######### Variáveis ##################################################

interface=$1
ip=$2
porta=$3
nomedehost=$4

######################################################################
### Remover alguns arquivos ###

rm -f /home/aluno/.x2goclient/sessions
rm -f /opt/jtag/iniciar-jtag
rm -f /etc/init.d/desligar
rm -f /etc/network/interfaces
rm -f /usr/local/bin/matar
rm -f /etc/systemd/system/getty@tty6.service
rm -rf /etc/systemd/system/getty@tty6.service.d

######################################################################
# criar /etc/network/interfaces

cat << EOF >> /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
auto $interface
iface $interface inet dhcp
EOF

####################################################################
### Criar /home/aluno/.x2goclient/sessions #########################

cat << EOF >> /home/aluno/.x2goclient/sessions
[rancher]
speed=3
pack=16m-jpeg
quality=9
fstunnel=true
export=
iconvto=UTF-8
iconvfrom=ISO8859-1
useiconv=false
fullscreen=true
multidisp=false
display=1
maxdim=false
rdpclient=rdesktop
directrdpsettings=
width=800
height=600
dpi=96
setdpi=true
xinerama=false
clipboard=both
usekbd=true
type=auto
sound=true
soundsystem=pulse
startsoundsystem=true
soundtunnel=true
defsndport=true
sndport=4713
print=true
name=JPMSB
icon=:/img/icons/128x128/x2gosession.png
host=$ip
user=aluno
key=/home/aluno/.ssh/labalu-cli-aluno
rdpport=3389
sshport=$porta
autologin=false
krblogin=false
krbdelegation=false
directrdp=false
rootless=false
published=false
applications=WWWBROWSER, MAILCLIENT, OFFICE, TERMINAL
command=rancher
rdpoptions=
rdpserver=
xdmcpserver=localhost
usesshproxy=false
sshproxytype=SSH
sshproxyuser=
sshproxykeyfile=
sshproxyhost=
sshproxyport=22
sshproxysamepass=false
sshproxysameuser=false
sshproxyautologin=false
sshproxykrblogin=false

[rancher-som]
speed=3
pack=16m-jpeg
quality=9
fstunnel=true
export=
iconvto=UTF-8
iconvfrom=ISO8859-1
useiconv=false
fullscreen=true
multidisp=false
display=1
maxdim=false
rdpclient=rdesktop
directrdpsettings=
width=800
height=600
dpi=96
setdpi=true
xinerama=false
clipboard=both
usekbd=true
type=auto
sound=true
soundsystem=pulse
startsoundsystem=true
soundtunnel=true
defsndport=true
sndport=4713
print=true
name=JPMSB
icon=:/img/icons/128x128/x2gosession.png
host=$ip
user=aluno
key=/home/aluno/.ssh/labalu-cli-aluno
rdpport=3389
sshport=$porta
autologin=false
krblogin=false
krbdelegation=false
directrdp=false
rootless=false
published=false
applications=WWWBROWSER, MAILCLIENT, OFFICE, TERMINAL
command=rancher-som
rdpoptions=
rdpserver=
xdmcpserver=localhost
usesshproxy=false
sshproxytype=SSH
sshproxyuser=
sshproxykeyfile=
sshproxyhost=
sshproxyport=22
sshproxysamepass=false
sshproxysameuser=false
sshproxyautologin=false
sshproxykrblogin=false
EOF

###################################################################################

chmod 550 /home/aluno/.x2goclient/sessions

###################################################################################

cat << EOF >> /opt/jtag/iniciar-jtag
# Inicia o jtagd e o jtagconfig habilitando o acesso remoto

/opt/jtag/bin/jtagd
/opt/jtag/bin/jtagconfig --enableremote rancheros
/usr/bin/ssh -i /root/.ssh/root -R 60000:localhost:1309 root@$ip -p $porta -N -f
EOF

###################################################################################

chmod 500 /opt/jtag/iniciar-jtag

###################################################################################

cat << EOF >> /etc/init.d/desligar
#!/bin/bash
### BEGIN INIT INFO
# Provides:          networking ifupdown
# Required-Start:    mountkernfs $local_fs urandom
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Raise network interfaces.
# Description:       Prepare /run/network directory, ifstate file and raise network interfaces, or take them down.
### END INIT INFO

ssh -p $porta -i /root/.ssh/root root@$ip killall -9 mate-session
# ssh -p $porta -i /root/.ssh/root root@$ip killall -9 mate-session
# ssh -p $porta -i /root/.ssh/root root@$ip killall -9 mate-session
# sleep 2
ssh -p $porta -i /root/.ssh/root root@$ip rm -rf /home/aluno
ssh -p $porta -i /root/.ssh/root root@$ip tar -zxvf /home/.aluno.tar.gz -C /home
ssh -p $porta -i /root/.ssh/root root@$ip chown -R aluno:aluno /home/aluno
ssh -p $porta -i /root/.ssh/root root@$ip chown -R root:root /home/aluno/.ssh/authorized_keys
ssh -p $porta -i /root/.ssh/root root@$ip chown -R root:root /home/aluno/.jtag.conf
ssh -p $porta -i /root/.ssh/root root@$ip echo "O sistema foi desligado em $(date)" >> /var/log/desligar.log
rm -rf /home/sdr
tar -zxvf /home/.sdr.tar.gz -C /home
rm -rf /home/aluno
tar -zxvf /home/.aluno.tar.gz -C /home
echo "O sistema foi desligado em $(date)" >> /var/log/desligar.log
EOF

############################################################################################

chmod 500 /etc/init.d/desligar

############################################################################################

cat << \EOF >> /etc/systemd/system/getty@tty6.service
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Getty on %I
Documentation=man:agetty(8) man:systemd-getty-generator(8)
Documentation=http://0pointer.de/blog/projects/serial-console.html
After=systemd-user-sessions.service plymouth-quit-wait.service
After=rc-local.service

# If additional gettys are spawned during boot then we should make
# sure that this is synchronized before getty.target, even though
# getty.target didn't actually pull it in.
Before=getty.target
IgnoreOnIsolate=yes

# IgnoreOnIsolate causes issues with sulogin, if someone isolates
# rescue.target or starts rescue.service from multi-user.target or
# graphical.target.
Conflicts=rescue.service
Before=rescue.service

# On systems without virtual consoles, don't start any getty. Note
# that serial gettys are covered by serial-getty@.service, not this
# unit.
ConditionPathExists=/dev/tty0

[Service]
# the VT is cleared by TTYVTDisallocate
ExecStart=-/sbin/agetty --autologin sdr --noclear %I $TERM
Type=idle
Restart=always
RestartSec=0
UtmpIdentifier=%I
TTYPath=/dev/%I
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
KillMode=process
IgnoreSIGPIPE=no
SendSIGHUP=yes

# Unset locale for the console getty since the console has problems
# displaying some internationalized messages.
Environment=LANG= LANGUAGE= LC_CTYPE= LC_NUMERIC= LC_TIME= LC_COLLATE= LC_MONETARY= LC_MESSAGES= LC_PAPER= LC_NAME= LC_ADDRESS= LC_TELEPHONE= LC_MEASUREMENT= LC_IDENTIFICATION=

[Install]
WantedBy=getty.target
DefaultInstance=tty6
EOF

############################################################################################

mkdir /etc/systemd/system/getty@tty6.service.d

############################################################################################
cat << EOF >> /etc/systemd/system/getty@tty6.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/usr/bin/ssh -i /root/.ssh/labalu-cli-aluno aluno@$ip -p $porta
StandardInput=tty
StandardOutput=tty
EOF

############################################################################################

cp /home/aluno/.ssh/labalu-cli-aluno /root/.ssh/
chmod 400 /root/.ssh/labalu-cli-aluno

############################################################################################

cat << EOF >> /usr/local/bin/matar
#!/bin/bash

if [ -z "${1}" ]; then

    echo "Sintaxe:"
    echo "sudo matar [APLICAÇÂO]"
    echo ""
    echo "    Aplicações:"
    echo ""
    echo "    firefox"
    echo "    spotify"
    echo "    vivaldi"

elif [ "$1" == "firefox" ]; then
    ssh -p $porta -i /root/.ssh/root root@172.18.20.200 killall -9 firefox

elif [ "$1" == "spotify" ]; then
    ssh -p $porta -i /root/.ssh/root root@$ip killall -9 spotify

elif [ "$1" == "vivaldi" ]; then
    ssh -p $porta -i /root/.ssh/root root@$ip killall -9 vivaldi
    ssh -p $porta -i /root/.ssh/root root@$ip killall -9 vivaldi-stable

else 
    echo "Não implementado."
fi
EOF

#########################################################################################

chmod 500 /usr/local/bin/matar

#########################################################################################

> /home/aluno/.xsession

#########################################################################################

cat << EOF >> /home/aluno/.xsession
#!/bin/bash

xterm -geometry 500x500 -bg black -fg black -e "exit"
yad --center --image="/usr/share/images/conectando.jpg" --no-buttons --auto-close --no-escape --undecorated &
timeout 1 ping -q -i 0.2 -c 2 $ip
EOF

cat << \EOF >> /home/aluno/.xsession
ping="$?"
EOF

cat << EOF >> /home/aluno/.xsession
echo $ping
nc -z -w5 $ip $porta
EOF

cat << \EOF >> /home/aluno/.xsession
nc="$?"
killall -9 yad

if [ "$ping" = "124" ] || [ "$ping" = "2" ]; then
    yad --center --image="/usr/share/images/conexao-servidor-fora.jpg" --button="Tentar novamente":0 --button="Desligar":"systemctl poweroff -i" --buttons-layout=center --no-escape --timeout=60 --timeout-indicator=bottom
    if [ "$?" = "0" ]; then
EOF

cat << EOF >> /home/aluno/.xsession
        sudo dhclient $interface
        /home/aluno/.xsession

    fi
EOF

cat << \EOF >> /home/aluno/.xsession
elif [ "$nc" = "0" ]; then
    test -e /home/aluno/.jpmsb

    if [ "$?" = "0" ]; then
        echo "Arquivo .jpmsb encontrado!!"
        conteudo_arquivo=$(cat /home/aluno/.jpmsb)
            if [ "$conteudo_arquivo" = "rancher" ]; then
                echo "Restaurando ambiente sem compartilhamento de som"
                yad --center --image="/usr/share/images/conectando-ambiente-trabalho.jpg" --no-buttons --auto-close --no-escape --undecorated &
                sleep 30 && killall -9 yad &
                x2goclient --hide --sessionid=rancher

            elif [ "$conteudo_arquivo" = "rancher-som" ]; then
                echo "Restaurando ambiente com compartilhamento de som"
                yad --center --image="/usr/share/images/conectando-ambiente-trabalho.jpg" --no-buttons --auto-close --no-escape --undecorated &
                /opt/SoundWireServer/SoundWireServer &
                sleep 30 && killall -9 yad &
                x2goclient --hide --sessionid=rancher-som

            fi
    elif [ "$?" = "1" ]; then
        echo "Início normal"
        xterm -geometry 500x500 -bg black -fg black -e "exit"
        yad --center --button="Cancelar":1 --button="Entendido":0 --image='/usr/share/images/informativo600.jpg'  --timeout=240 --timeout-indicator=bottom

        if [ "$?" = "0" ]; then
            yad --center --image="/usr/share/images/informativo-audio-permitir.jpg" --button="Recusar":1 --button="Permitir":0

            if [ "$?" = "0" ]; then
                echo "rancher-som" > /home/aluno/.jpmsb
                yad --center --image="/usr/share/images/conectando-ambiente-trabalho.jpg" --no-buttons --auto-close --no-escape --undecorated &
                /opt/SoundWireServer/SoundWireServer &
                sleep 30 && killall -9 yad &
                x2goclient --hide --sessionid=rancher-som

            elif [ "$?" = "1" ]; then
                echo "rancher" > /home/aluno/.jpmsb
                yad --center --image="/usr/share/images/conectando-ambiente-trabalho.jpg" --no-buttons --auto-close --no-escape --undecorated &
                sleep 30 && killall -9 yad &
                x2goclient --hide --sessionid=rancher

            fi

        elif [ "$?" = "1" ]; then
            systemctl poweroff -i

        fi
    fi

elif [ "$ping" = "0" ] && [ "$nc" = "1" ]; then
    yad --center --image="/usr/share/images/conexao-porta-fora.jpg" --button="Ok":"systemctl poweroff -i" --buttons-layout=center --no-escape --timeout=60 --timeout-indicator=bottom

fi
EOF

##########################################################################################

rm -f /etc/sudoers

##########################################################################################

cat << EOF >> /etc/sudoers
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL
sdr     ALL=(ALL) NOPASSWD: /usr/bin/rtl_tcp
aluno   ALL=(ALL) NOPASSWD: /sbin/dhclient $interface

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
EOF

##########################################################################################

chmod 440 /etc/sudores

##########################################################################################

echo "$nomedehost" > /etc/hostname

##########################################################################################

rm -r /root/.ssh/known_hosts
rm -r /home/aluno/.x2go
# tar -zcvf /home/.aluno.tar.gz -C /home aluno
# tar -zxvf /home/.aluno.tar.gz -C /home
chown root:especial /home/aluno/.profile
chmod 550 /home/aluno/.profile
chown root:especial /home/aluno/.bash_profile
chmod 550 /home/aluno/.bash_profile
chown root:especial /home/aluno/.xinitrc
chmod 550 /home/aluno/.xinitrc
chown root:especial /home/aluno/.xsession
chmod 550 /home/aluno/.xsession
chown -R root:especial /home/aluno/.x2goclient
chmod -R 550 /home/aluno/.x2goclient
chown root:especial /home/aluno/.ssh/labalu-cli-aluno
chmod 440 /home/aluno/.ssh/labalu-cli-aluno
chown root:especial /home/aluno/.bashrc
chmod 550 /home/aluno/.bashrc

###########################################################################################
rm -r /home/aluno/.jpmsb
rm -r /home/aluno/.x2go
tar -zcvf /home/.aluno.tar.gz -C /home aluno
