#!/bin/bash

rm -r /root/.x2goclient
mkdir /root/.x2goclient

IP=`echo $SSH_CONNECTION | cut -f1 -d " "`
USUARIO=$(echo $PWD |cut -f3 -d "/")
porta=22

cat << EOF >> /root/.x2goclient/sessions
[arduino]
speed=3
pack=16m-jpeg
quality=9
fstunnel=true
export=
iconvto=UTF-8
iconvfrom=ISO8859-1
useiconv=false
fullscreen=true
multidisp=false
display=1
maxdim=false
rdpclient=rdesktop
directrdpsettings=
width=800
height=600
dpi=96
setdpi=true
xinerama=true
clipboard=both
usekbd=true
type=auto
sound=true
soundsystem=pulse
startsoundsystem=true
soundtunnel=true
defsndport=true
sndport=4713
print=true
name=JPMSB
icon=:/img/icons/128x128/x2gosession.png
host=$IP
user=arduino
key=/root/.ssh/labalu-cli-aluno
rdpport=3389
sshport=$porta
autologin=false
krblogin=false
krbdelegation=false
directrdp=false
rootless=true
published=false
applications=/opt/arduino/arduino, WWWBROWSER, MAILCLIENT, OFFICE, TERMINAL
command=/opt/arduino/arduino
rdpoptions=
rdpserver=
xdmcpserver=localhost
usesshproxy=false
sshproxytype=SSH
sshproxyuser=
sshproxykeyfile=
sshproxyhost=
sshproxyport=22
sshproxysamepass=false
sshproxysameuser=false
sshproxyautologin=false
sshproxykrblogin=false
xdmcpclient=Xnest
directxdmcpsettings=
directxdmcp=false
EOF

HOME=/root
x2goclient --hide --add-to-known-hosts --sessionid=arduino
