#!/bin/bash

destino=$1

if [ -z "${destino}" ]; then
    echo -e "\e[1;31mFalta especificar o destino!!!!\e[0m"
    echo "Uso: atualizar-firefox destino"
    echo "Ex.: atualizar-firefox /opt"

    exit 1

fi

curl -sL https://download-installer.cdn.mozilla.net/pub/firefox/releases/ >  /mozilla
versao=$(html2text /mozilla |cut -f3 -d " " | cut -f1 -d "." | sort -rn | head -n 1)
versao_corrigida=$((versao - 1))
versao_atual=$(html2text /mozilla |cut -f3 -d " " |grep $versao_corrigida |sort -rn |head -n 1 |cut -f1 -d "/")
rm -r /mozilla

versao_instalada=$(cat $destino/firefox/versionamento 2> /dev/null || echo 0)

if [ "$versao_atual" = "$versao_instalada" ]; then
    echo -e "\e[1;32mNada precisa ser feito :)\e[0m"
    echo "[$(date +%d/%m/%Y) - $(date +%T)] - Nada precisa ser feito :)" >> /var/log/atualizar-firefox.log

else
    echo -e "\e[1;93mEncontrado \e[1;96mfirefox-$versao_atual\e[0m \e[1;93mcomo mais recente.\e[0m"
    echo -e "\e[1;93mBaixando \e[1;96mfirefox-$versao_atual.tar.bz2\e[0m \e[1;93m...\e[0m"
    echo "[$(date +%d/%m/%Y) - $(date +%T)] - Encontrado firefox-$versao_atual como mais recente." >> /var/log/atualizar-firefox.log
    
    wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/$versao_atual/linux-x86_64/pt-BR/firefox-$versao_atual.tar.bz2 firefox -O /firefox-$versao_atual.tar.bz2
    
    tar -xvf /firefox-$versao_atual.tar.bz2 -C /
    rm -r $destino/firefox
    mv /firefox $destino/firefox
    echo "$versao_atual" > $destino/firefox/versionamento
    rm -r /firefox-$versao_atual.tar.bz2
    ln -s $destino/firefox/firefox /usr/local/bin/firefox 2> /dev/null
    
    echo -e "\e[1;32mInstalado com sucesso!!!\e[0m"
    echo "[$(date +%d/%m/%Y) - $(date +%T)] - Instalado com sucesso!!!" >> /var/log/atualizar-firefox.log

fi
