#!/bin/bash

rm /tmp/kflj.*
arquivo_de_trocadilhos=$(mktemp /tmp/kflj.XXXXXXX)
export arquivo_de_trocadilhos=$arquivo_de_trocadilhos
curl -sL raw.githubusercontent.com/jpmsb/dicas/master/trocadilhos > $arquivo_de_trocadilhos
sorteador $arquivo_de_trocadilhos
